FIX: pin to the old version we were on and for good measure, install curl manually

diff --git a/Dockerfile.cpu b/Dockerfile.cpu
--- a/Dockerfile.cpu
+++ b/Dockerfile.cpu
@@ -1,40 +1,14 @@
 # TensorFlow image has GPU support and Jupyter
-FROM tensorflow/tensorflow:latest-py3
-
-# Be root for some reason.
-#USER root
-
-# Try to do everything via conda
-#RUN bash -c 'source activate base && conda install git pip nodejs -y'
-
-# Install JupyterLab
-#RUN bash -c 'source activate base && pip install jupyterlab'
-#RUN bash -c 'source activate base && jupyter serverextension enable --py jupyterlab'
-
-# Install Python library for Data Science
-#RUN bash -c 'source activate base && pip --no-cache-dir install \
-#        plotly \
-#        Pillow \
-#        google-api-python-client'
-
-# Set up Jupyter Notebook config
-#ENV CONFIG /home/jovyan/.jupyter/jupyter_notebook_config.py
-#ENV CONFIG_IPYTHON /home/jovyan/.ipython/profile_default/ipython_config.py
-
-#RUN bash -c 'source activate base && rm /home/jovyan/.jupyter/jupyter_notebook_config.py && jupyter notebook --generate-config --allow-root && \
-#    ipython profile create'
-
-#RUN echo "c.NotebookApp.ip = '*'" >>${CONFIG} && \
-#    echo "c.NotebookApp.open_browser = False" >>${CONFIG} && \
-#    echo "c.NotebookApp.iopub_data_rate_limit=10000000000" >>${CONFIG} && \
-#    echo "c.MultiKernelManager.default_kernel_name = 'python3'" >>${CONFIG}
-
-#RUN echo "c.InteractiveShellApp.exec_lines = ['%matplotlib inline']" >>${CONFIG_IPYTHON}
+FROM tensorflow/tensorflow:1.12.0-py3
 
 # ==== OUR STUFF FOLLOWS ====
 ENV last-update "2019-02-18 11:54"
 
+RUN apt-get install -y curl
+
 # Node
+# make it so that if the curl command fails we aren't screwed
+RUN set -euxo pipefail
 RUN curl -sL https://deb.nodesource.com/setup_8.x |bash
 RUN apt-get update && apt-get install -y git nodejs
 
